version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server

    ports:
      - "8080:80"  # Map host port 8080 -> container port 80

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom config
      - ./html:/usr/share/nginx/html:ro     # Serve static files
    
    depends_on:
      - redis

    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  redis_data: {}

networks:
  backend: {}